### ISSUE TITLE
Esto solo funciona con Katana? 

### ISSUE THREAD

**Issue by borisgr04** [IdentityServer/CrossVersionIntegrationTests#3]
Esto solo funciona con Katana? 

This only works with Katana?

**Comment by brockallen** [comment]
This repo is meant to show the combination of IS3 working with our ASP.NET Core authentication handler, and IS4 working with our Katana authentication middleware. In other words, you can use IS3 with newer APIs and IS4 with older APIs

**Comment by borisgr04** [comment]
Español: Mi pregunta no fue la Mejor. Pregunto de Nuevo, es que no soy experto en el tema de Katana.

Se puede usar este con API .NetFramework hospedadas en IIS usando Microsoft.Owin.Host.SystemWeb  o solo en sitios Auto Hospedados

**Comment by brockallen** [comment]
Sorry we missed this issue. I'm sure you have figured it out by now, but this can be used in IIS.
