### ISSUE TITLE
Failure on Sign-in with Azure AD

### ISSUE THREAD

**Issue by sneckelmann** [IdentityServer/CrossVersionIntegrationTests#4]
Navigated to managed stored grants from https://demo.identityserver.io/

Selected "Sign-in with Azure AD"

Error from MS:

> AADSTS700016: Application with identifier 'https://leastprivilegelabs.onmicrosoft.com/38196330-e766-4051-ad10-14596c7e97d3' was not found in the directory '012a0d6b-2602-4786-8528-cd4049164454'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant

**Comment by topn0tch** [comment]
Any news on this? I'm also getting this error. However, no problems when using an incognito browser.

**Comment by leastprivilege** [comment]
I think I deleted this app in Azure a long time ago.
