### ISSUE TITLE
IdentityServer3.AccessTokenValidation nuget package unlisted 

### ISSUE THREAD

**Issue by theythinkimmexican** [IdentityServer/CrossVersionIntegrationTests#6]
Hello,

It seems as though the IdentityServer3.AccessTokenValidation 2.15.1 package has been unlisted from nuget - https://www.nuget.org/packages/IdentityServer3.AccessTokenValidation/2.15.1

When trying to reinstall nuget packages I noticed a failure "Unable to find package 'IdentityServer3.AccessTokenValidation'" and right enough it seems like that version of the package has been removed and the latest version is now 2.14.0

Was this done deliberately? It seems like this would have happened within the last few months but I can see any documentation around when or why it was removed.

**Comment by brockallen** [comment]
Yes, there was a bug that's why we unlisted.

**Comment by theythinkimmexican** [comment]
ok so is it recommended to just downgrade to v2.14?

**Comment by brockallen** [comment]
that's the implication

**Comment by theythinkimmexican** [comment]
ok, thank you.

**Comment by brockallen** [comment]
If you want to update the version in this repo with a PR, then it would be appreciated.
